// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/.well-known/jwks.json": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Chiave pubblica per verificare i JWT (formato JWKS)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "tags": [
                    "system"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "Service healthy"
                    },
                    "503": {
                        "description": "Database unreachable"
                    }
                }
            }
        },
        "/v1/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Email o username + password",
                        "name": "credenziali",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Payload non valido"
                    },
                    "401": {
                        "description": "Credenziali non valide"
                    }
                }
            }
        },
        "/v1/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Profilo dell'utente autenticato",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_anagrafica_internal_user.User"
                        }
                    },
                    "401": {
                        "description": "Autenticazione richiesta"
                    }
                }
            }
        },
        "/v1/password/cambia": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Cambia la password dell'utente autenticato",
                "parameters": [
                    {
                        "description": "Vecchia e nuova password",
                        "name": "password",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.changePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Password cambiata"
                    },
                    "400": {
                        "description": "Payload non valido"
                    },
                    "401": {
                        "description": "Vecchia password non corretta"
                    }
                }
            }
        },
        "/v1/utenti": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utenti"
                ],
                "summary": "Crea un nuovo utente (solo amministratori)",
                "parameters": [
                    {
                        "description": "Email, username, ruoli (slug)",
                        "name": "utente",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.createUserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.createUserResponse"
                        }
                    },
                    "400": {
                        "description": "Payload non valido o ruolo sconosciuto"
                    },
                    "403": {
                        "description": "Permesso di amministrazione richiesto"
                    },
                    "409": {
                        "description": "Email o username già in uso"
                    }
                }
            }
        },
        "/v1/utenti/attiva": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "utenti"
                ],
                "summary": "Attiva un account tramite il token di invito, impostando la password",
                "parameters": [
                    {
                        "description": "Token di invito e nuova password",
                        "name": "attivazione",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.activateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Account attivato"
                    },
                    "400": {
                        "description": "Payload non valido"
                    },
                    "401": {
                        "description": "Token non valido, scaduto o già usato"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_francescocerri_sanitas_services_anagrafica_internal_user.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_httpapi.activateUserRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_httpapi.changePasswordRequest": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "internal_httpapi.createUserRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_httpapi.createUserResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "invite_url": {
                    "description": "InviteURL is handed back directly in this response instead of being\nemailed: sending it for real (Gmail SMTP) is a separate follow-up\nactivity, this phase only lays the token groundwork. The admin\nforwards it to the volunteer by whatever channel they already use.",
                    "type": "string"
                },
                "is_admin": {
                    "type": "boolean"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "internal_httpapi.loginRequest": {
            "type": "object",
            "properties": {
                "identifier": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Sanitas — Anagrafica API",
	Description:      "Utenti, ruoli, autenticazione. Fase A: creazione utenti da amministratore,\nattivazione via token, login, cambio password. L'invio email reale\n(inviti/forgot-password) è una fase successiva — vedi docs/adr/0013.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
