// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "tags": [
                    "system"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "Service healthy"
                    },
                    "503": {
                        "description": "Database unreachable"
                    }
                }
            }
        },
        "/v1/shifts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shifts"
                ],
                "summary": "List shifts (requires the shifts:read permission)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_francescocerri_sanitas_services_shifts_internal_shift.Shift"
                            }
                        }
                    },
                    "401": {
                        "description": "Authentication required"
                    },
                    "403": {
                        "description": "Missing required permission: shifts:read"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shifts"
                ],
                "summary": "Create a new shift (requires the shifts:write permission)",
                "parameters": [
                    {
                        "description": "New shift (id and status in the input are ignored)",
                        "name": "shift",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_shifts_internal_shift.Shift"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_shifts_internal_shift.Shift"
                        }
                    },
                    "400": {
                        "description": "Invalid payload"
                    },
                    "401": {
                        "description": "Authentication required"
                    },
                    "403": {
                        "description": "Missing required permission: shifts:write"
                    }
                }
            }
        },
        "/v1/shifts/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shifts"
                ],
                "summary": "Get a shift by id (requires the shifts:read permission)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Shift id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_shifts_internal_shift.Shift"
                        }
                    },
                    "401": {
                        "description": "Authentication required"
                    },
                    "403": {
                        "description": "Missing required permission: shifts:read"
                    },
                    "404": {
                        "description": "Shift not found"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_francescocerri_sanitas_services_shifts_internal_shift.Shift": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "volunteer_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "shifts issues no tokens itself — type \"Bearer\" followed by a space and\nthe access token obtained from registry's POST /v1/login (e.g. \"Bearer eyJhbGci...\").",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Sanitas — Shifts API",
	Description:      "Shift management. The data model is intentionally skeletal (see docs/adr/0005\nin the repository): it validates the end-to-end pipeline, not the final domain design.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
