// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "tags": [
                    "system"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "Service healthy"
                    },
                    "503": {
                        "description": "Database unreachable"
                    }
                }
            }
        },
        "/v1/shift-bookings": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shift-bookings"
                ],
                "summary": "Request a booking for an open slot (requires the shifts:request permission)",
                "parameters": [
                    {
                        "description": "Template id and date (YYYY-MM-DD)",
                        "name": "booking",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.createBookingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_shifts_internal_shift.Booking"
                        }
                    },
                    "400": {
                        "description": "Invalid payload, past date, inactive template, or weekday mismatch"
                    },
                    "401": {
                        "description": "Authentication required"
                    },
                    "403": {
                        "description": "Missing required permission: shifts:request"
                    },
                    "404": {
                        "description": "Template not found"
                    },
                    "409": {
                        "description": "Slot already confirmed, or the caller already has a pending/confirmed booking for it"
                    }
                }
            }
        },
        "/v1/shift-bookings/pending-count": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shift-bookings"
                ],
                "summary": "Count pending booking requests (requires the shifts:write permission)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.pendingBookingsCountResponse"
                        }
                    },
                    "401": {
                        "description": "Authentication required"
                    },
                    "403": {
                        "description": "Missing required permission: shifts:write"
                    }
                }
            }
        },
        "/v1/shift-occurrences": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shift-occurrences"
                ],
                "summary": "List shift occurrences with coverage status in a date range (requires the shifts:read permission)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date, inclusive (YYYY-MM-DD)",
                        "name": "from",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "End date, inclusive (YYYY-MM-DD)",
                        "name": "to",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_francescocerri_sanitas_services_shifts_internal_shift.Occurrence"
                            }
                        }
                    },
                    "400": {
                        "description": "Missing or invalid from/to, or range too wide"
                    },
                    "401": {
                        "description": "Authentication required"
                    },
                    "403": {
                        "description": "Missing required permission: shifts:read"
                    }
                }
            }
        },
        "/v1/shift-templates": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shift-templates"
                ],
                "summary": "List shift templates (requires the shifts:read permission)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_francescocerri_sanitas_services_shifts_internal_shift.ShiftTemplate"
                            }
                        }
                    },
                    "401": {
                        "description": "Authentication required"
                    },
                    "403": {
                        "description": "Missing required permission: shifts:read"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shift-templates"
                ],
                "summary": "Create a shift template (requires the shifts:configure permission)",
                "parameters": [
                    {
                        "description": "Weekday (0=Sunday..6=Saturday), start/end time (HH:MM), label",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.createTemplateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_shifts_internal_shift.ShiftTemplate"
                        }
                    },
                    "400": {
                        "description": "Invalid payload"
                    },
                    "401": {
                        "description": "Authentication required"
                    },
                    "403": {
                        "description": "Missing required permission: shifts:configure"
                    }
                }
            }
        },
        "/v1/shift-templates/{id}": {
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shift-templates"
                ],
                "summary": "Replace a shift template (requires the shifts:configure permission)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Template id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Full new set of fields",
                        "name": "template",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_httpapi.updateTemplateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_shifts_internal_shift.ShiftTemplate"
                        }
                    },
                    "400": {
                        "description": "Invalid payload"
                    },
                    "401": {
                        "description": "Authentication required"
                    },
                    "403": {
                        "description": "Missing required permission: shifts:configure"
                    },
                    "404": {
                        "description": "Template not found"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_francescocerri_sanitas_services_shifts_internal_shift.Booking": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "decided_at": {
                    "type": "string"
                },
                "decided_by": {
                    "description": "DecidedBy/DecidedAt stay nil while the request is pending; for a\nmanager's direct booking (no approval needed) they're already set at\ncreation time.",
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_francescocerri_sanitas_services_shifts_internal_shift.BookingStatus"
                },
                "template_id": {
                    "type": "string"
                },
                "volunteer_id": {
                    "type": "string"
                }
            }
        },
        "github_com_francescocerri_sanitas_services_shifts_internal_shift.BookingStatus": {
            "type": "string",
            "enum": [
                "pending",
                "confirmed",
                "rejected",
                "cancelled"
            ],
            "x-enum-varnames": [
                "BookingStatusPending",
                "BookingStatusConfirmed",
                "BookingStatusRejected",
                "BookingStatusCancelled"
            ]
        },
        "github_com_francescocerri_sanitas_services_shifts_internal_shift.Occurrence": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "end_time": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/github_com_francescocerri_sanitas_services_shifts_internal_shift.OccurrenceStatus"
                },
                "template_id": {
                    "type": "string"
                },
                "weekday": {
                    "type": "integer"
                }
            }
        },
        "github_com_francescocerri_sanitas_services_shifts_internal_shift.OccurrenceStatus": {
            "type": "string",
            "enum": [
                "free",
                "pending",
                "confirmed"
            ],
            "x-enum-varnames": [
                "OccurrenceStatusFree",
                "OccurrenceStatusPending",
                "OccurrenceStatusConfirmed"
            ]
        },
        "github_com_francescocerri_sanitas_services_shifts_internal_shift.ShiftTemplate": {
            "type": "object",
            "properties": {
                "active": {
                    "description": "No DB default (` + "`" + `default:true` + "`" + `): for a bool field, GORM omits a Go\nzero value (false) from the INSERT and the DB default would still\napply — a caller explicitly wanting ` + "`" + `false` + "`" + ` would be silently\nignored. The repository sets Active by hand at creation (see\nCreateTemplate), same principle already used for Booking.Status.",
                    "type": "boolean"
                },
                "end_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "label": {
                    "description": "Cosmetic, shown in the UI (e.g. \"Turno 3\") — empty string allowed,\ndoesn't drive any logic.",
                    "type": "string"
                },
                "start_time": {
                    "description": "\"HH:MM\". EndTime \u003c StartTime means an overnight shift spanning two\ndays (e.g. 20:00-08:00) — these are times of day, not timestamps: no\ntime.Time here, sidesteps timezone/fake-date concerns for a value\nthat's only ever \"what time of day\".",
                    "type": "string"
                },
                "weekday": {
                    "description": "Weekday follows Go's time.Weekday (0=Sunday...6=Saturday): reuses a\nstdlib conversion for generating occurrences instead of inventing a\nnumbering scheme to remember.",
                    "type": "integer"
                }
            }
        },
        "internal_httpapi.createBookingRequest": {
            "type": "object",
            "properties": {
                "date": {
                    "type": "string"
                },
                "template_id": {
                    "type": "string"
                }
            }
        },
        "internal_httpapi.createTemplateRequest": {
            "type": "object",
            "properties": {
                "end_time": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "weekday": {
                    "type": "integer"
                }
            }
        },
        "internal_httpapi.pendingBookingsCountResponse": {
            "type": "object",
            "properties": {
                "pending_count": {
                    "type": "integer"
                }
            }
        },
        "internal_httpapi.updateTemplateRequest": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "end_time": {
                    "type": "string"
                },
                "label": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "weekday": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "shifts issues no tokens itself — type \"Bearer\" followed by a space and\nthe access token obtained from registry's POST /v1/login (e.g. \"Bearer eyJhbGci...\").",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Sanitas — Shifts API",
	Description:      "Shift management. Recurring shift templates (day of week + time range) and\nvolunteer bookings against them — see docs/adr/0025-modello-dati-turni.md in\nthe repository. The resource endpoints themselves are still being rebuilt on\ntop of this model (see docs/backlog.md); only /healthz and /docs/ exist today.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
