// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "tags": [
                    "sistema"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "Servizio operativo"
                    },
                    "503": {
                        "description": "Database non raggiungibile"
                    }
                }
            }
        },
        "/turni": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turni"
                ],
                "summary": "Elenca i turni",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_francescocerri_sanitas_services_turni_internal_turno.Turno"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turni"
                ],
                "summary": "Crea un nuovo turno",
                "parameters": [
                    {
                        "description": "Nuovo turno (id e stato in input vengono ignorati)",
                        "name": "turno",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_turni_internal_turno.Turno"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_turni_internal_turno.Turno"
                        }
                    },
                    "400": {
                        "description": "Payload non valido"
                    }
                }
            }
        },
        "/turni/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turni"
                ],
                "summary": "Recupera un turno per id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID del turno (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_turni_internal_turno.Turno"
                        }
                    },
                    "404": {
                        "description": "Turno non trovato"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_francescocerri_sanitas_services_turni_internal_turno.Turno": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ora_fine": {
                    "type": "string"
                },
                "ora_inizio": {
                    "type": "string"
                },
                "stato": {
                    "type": "string"
                },
                "volontario_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Sanitas — Turni API",
	Description:      "Gestione turni. Modello dati volutamente scheletrico (vedi docs/adr/0005 nel repository):\nvalida la pipeline end-to-end, non è la progettazione definitiva del dominio.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
