// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "tags": [
                    "system"
                ],
                "summary": "Liveness check",
                "responses": {
                    "200": {
                        "description": "Service healthy"
                    },
                    "503": {
                        "description": "Database unreachable"
                    }
                }
            }
        },
        "/turni": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turni"
                ],
                "summary": "List turni",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/github_com_francescocerri_sanitas_services_turni_internal_turno.Turno"
                            }
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turni"
                ],
                "summary": "Create a new turno",
                "parameters": [
                    {
                        "description": "New turno (id and stato in the input are ignored)",
                        "name": "turno",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_turni_internal_turno.Turno"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_turni_internal_turno.Turno"
                        }
                    },
                    "400": {
                        "description": "Invalid payload"
                    }
                }
            }
        },
        "/turni/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "turni"
                ],
                "summary": "Get a turno by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Turno id (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_francescocerri_sanitas_services_turni_internal_turno.Turno"
                        }
                    },
                    "404": {
                        "description": "Turno not found"
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_francescocerri_sanitas_services_turni_internal_turno.Turno": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ora_fine": {
                    "type": "string"
                },
                "ora_inizio": {
                    "type": "string"
                },
                "stato": {
                    "type": "string"
                },
                "volontario_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Sanitas — Turni API",
	Description:      "Turno (shift) management. The data model is intentionally skeletal (see docs/adr/0005\nin the repository): it validates the end-to-end pipeline, not the final domain design.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
