package shift

// ShiftTemplate is a recurring shift configured by the shift manager (day of
// week + time range), not a concrete event — see
// docs/adr/0025-modello-dati-turni.md. Concrete occurrences over a date
// range are generated by combining active templates with the calendar (see
// the "API: calendario e copertura" backlog item), not rows of this table.
type ShiftTemplate struct {
	ID string `gorm:"type:uuid;primaryKey;default:gen_random_uuid()" json:"id,omitempty"`
	// Weekday follows Go's time.Weekday (0=Sunday...6=Saturday): reuses a
	// stdlib conversion for generating occurrences instead of inventing a
	// numbering scheme to remember.
	Weekday int `gorm:"not null;check:weekday BETWEEN 0 AND 6" json:"weekday"`
	// "HH:MM". EndTime < StartTime means an overnight shift spanning two
	// days (e.g. 20:00-08:00) — these are times of day, not timestamps: no
	// time.Time here, sidesteps timezone/fake-date concerns for a value
	// that's only ever "what time of day".
	StartTime string `gorm:"column:start_time;not null" json:"start_time"`
	EndTime   string `gorm:"column:end_time;not null" json:"end_time"`
	// Cosmetic, shown in the UI (e.g. "Turno 3") — empty string allowed,
	// doesn't drive any logic.
	Label string `gorm:"not null" json:"label"`
	// No DB default (`default:true`): for a bool field, GORM omits a Go
	// zero value (false) from the INSERT and the DB default would still
	// apply — a caller explicitly wanting `false` would be silently
	// ignored. The repository sets Active by hand at creation (see
	// CreateTemplate), same principle already used for Booking.Status.
	Active bool `gorm:"not null" json:"active"`
}

func (ShiftTemplate) TableName() string { return "shift_templates" }
