package httpapi

import (
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger/v2"

	// Side effect: registers the spec generated by swag (api/docs.go,
	// derived from the annotations above the handlers) in the registry read
	// by http-swagger. Regenerate with `swag init` after changing any
	// annotation — a CI check verifies you didn't forget to.
	_ "github.com/francescocerri/sanitas/services/registry/api"
)

// docsHandler serves the Swagger UI (assets embedded in the library, no
// external CDN dependency) on /docs/, backed by the generated spec.
func docsHandler() http.Handler {
	return httpSwagger.Handler(httpSwagger.URL("/docs/doc.json"))
}
